INSERT INTO public.exercise_library (name, link) VALUES
('corrida', 'https://drive.google.com/file/d/1EyEo14GnK7_oMUKZCff7LOFgfcsWaAo9/view?usp=sharing'),
('alongamento', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('mobilidade', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('ativação e mobilidade', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('rotação de ombro', 'https://www.youtube.com/watch?v=YD2EevxIu_Q'),
('foam roller', 'https://www.youtube.com/watch?v=Orfqe-CQIZo'),
('salto de corda', 'https://www.youtube.com/watch?v=82jNjDS19lg'),
('salto de corda - terça', 'https://www.youtube.com/watch?v=82jNjDS19lg'),
('condicionamento metabólico (metcon)', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
('amrap', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
('band pull-apart', 'https://www.youtube.com/shorts/SuvO4TBwSu4'),
('dumbbell floor press', 'https://www.youtube.com/shorts/UBmpZ7l5Nlk'),
('plank + bike', 'https://www.youtube.com/watch?v=L2jO3DvocWA'),
('rotação externa', 'https://www.youtube.com/shorts/AUboK3H5EO8'),
('ativações de glúteo', 'https://www.youtube.com/shorts/NEZu5shljRg'),
('bike', 'https://drive.google.com/file/d/1nsWhiyaEPMuauziOdkZhepHdan-_IeER/view?usp=drive_link'),
('crossfit', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=sharing'),
('dumbbell bench press', 'https://www.youtube.com/shorts/2AopA8XXMDw'),
('deadlift', 'https://www.youtube.com/watch?v=l6gDwf3xC6s'),
('front squat', 'https://www.youtube.com/watch?v=uYumuL_G_V0'),
('dumbell reverse lunge', 'https://www.youtube.com/shorts/mzPFverp8tM'),
('mobilidade de tornozelo e quadril', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('wall slides', 'https://www.youtube.com/shorts/i_0zLUcE-zk'),
('ponte de glúteos', 'https://www.youtube.com/shorts/4_PBAwcqrZo'),
('ponte de glúteo unilateral', 'https://www.youtube.com/shorts/0e1SXFq806U'),
('agachamento isométrico', 'https://www.youtube.com/shorts/y0Tk1G0cDac'),
('scapular push-ups', 'https://www.youtube.com/watch?v=huGj4aBk9C4'),
('serratus punches (com anilha)', 'https://www.youtube.com/watch?v=M-vsEfJIoWE'),
('copenhagen plank', 'https://www.youtube.com/watch?v=5Hs7AfiMXgs'),
('alongamento de peitoral', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('rolo de liberação', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('movimentos articulares livres', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('pass-through com bastão', 'https://www.youtube.com/shorts/UaMYy8Hx_3M'),
('mobilidade de punho', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('alongamento de panturrilhas', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('rotações externas com elástico', 'https://www.youtube.com/shorts/AUboK3H5EO8'),
('ativações de glúteo com miniband', 'https://www.youtube.com/shorts/NEZu5shljRg'),
('alongamento de posteriores e grande dorsal', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('corrida de Recuperação', 'https://drive.google.com/file/d/1EyEo14GnK7_oMUKZCff7LOFgfcsWaAo9/view?usp=sharing'),
('back squat', 'https://www.youtube.com/watch?v=QmZAiBqPvZw'),
('romanian deadlift (rdl)', 'https://www.youtube.com/shorts/up0sPrYCTkI'),
('supino com halteres', 'https://www.youtube.com/shorts/hlV6f0kHmeo'),
('landmine press', 'https://www.youtube.com/watch?v=6cSTRPhpubs'),
('remada curvada com barra', 'https://www.youtube.com/shorts/T7Xlz9AlD-A'),
('facepull', 'https://www.youtube.com/shorts/-iPCIEEl_X4'),
('progressão de barra fixa', 'https://www.youtube.com/shorts/BYYxtz9MtDc'),
('flexão de braço', 'https://www.youtube.com/shorts/pRzxpe5_LLk'),
('dumbbell front squat', 'https://www.youtube.com/watch?v=rotBMUQHdZk'),
('desenvolvimento com halteres sentado', 'https://www.youtube.com/shorts/TLvK2UExsD8'),
('snatch grip rdl', 'https://www.youtube.com/watch?v=5S8dfigc3iE'),
('snatch high pull', 'https://www.youtube.com/watch?v=ZWDlo2Lj7Wo'),
('muscle snatch', 'https://www.youtube.com/watch?v=bJYzOo1cNqY'),
('clean grip rdl', 'https://www.youtube.com/watch?v=A9vCfTTMndA'),
('clean high pull', 'https://www.youtube.com/watch?v=psI4A7bc7Fo'),
('tall cleans', 'https://www.youtube.com/shorts/3vcQTLooWM4'),
('remadas com halteres', 'https://www.youtube.com/shorts/mjFIZX68F_8'),
('back lunges (sem peso)', 'https://www.youtube.com/shorts/38xlLGfguz4'),
('burpees', 'https://www.youtube.com/watch?v=TU8QYVW0gDU'),
('alongamento de quadríceps e posteriores de coxa', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('alongamento pigeon pose', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('alongamentos leves para peitoral e costas', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('Relaxamento na água', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('air squat', 'https://www.youtube.com/watch?v=C_VtOYc6j5c'),
('alongamento completo', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
('australian pull-up', 'https://www.youtube.com/watch?v=RTG1EYU8EGY'),
('bulgarian split squat', 'https://www.youtube.com/watch?v=vgn7bSXkgkA'),
('cachorro + cobra', 'https://www.youtube.com/watch?v=k48O2CxvZ3o'),
('cadeira abdutora', 'https://www.youtube.com/watch?v=50qHGus1TZk'),
('dead bug', 'https://www.youtube.com/watch?v=jbWmbhElf3Q'),
('elevação panturrilha', 'https://www.youtube.com/watch?v=cklp_Xh5V8M'),
('equilíbrio unilateral', 'https://www.youtube.com/watch?v=ZfXQC3FfX5o'),
('facepull miniband', 'https://www.youtube.com/watch?v=XVL0yXpKsek'),
('gato-vaca', 'https://www.youtube.com/watch?v=40Y1rukJs4E'),
('ghd back extension', 'https://www.youtube.com/watch?v=xMyFXMZ6Ch0'),
('ghd sit up', 'https://www.youtube.com/watch?v=pMS2dU0FuPk'),
('glute bridge march', 'https://www.youtube.com/watch?v=msfdrPWJ-9o'),
('hollow rock', 'https://www.youtube.com/watch?v=p7j02V1fIzU'),
('jumping lunge', 'https://www.youtube.com/watch?v=iJMsF7fzrOM'),
('leg press unilateral', 'https://www.youtube.com/watch?v=S6i3fG4Trs0'),
    ('liberação escapular', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
    ('liberação peitoral', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
    ('lunge', 'https://www.youtube.com/watch?v=tTej-ax9XiA'),
    ('mesa flexora', 'https://www.youtube.com/shorts/IRz4e6uYAGU'),
    ('mobilidade 90/90', 'https://www.youtube.com/watch?v=juOtDljPfws'),
    ('mobilidade t-spine + quadril', 'https://www.youtube.com/watch?v=AHEUZSd8hD0'),
    ('natação', 'https://drive.google.com/file/d/15emDzhbTMen-bnpQxKsn1EnxPRKimZag/view?usp=sharing'),
    ('natação - cooldown', 'https://drive.google.com/file/d/15emDzhbTMen-bnpQxKsn1EnxPRKimZag/view?usp=sharing'),
    ('natação - warmup', 'https://drive.google.com/file/d/15emDzhbTMen-bnpQxKsn1EnxPRKimZag/view?usp=sharing'),
    ('pallof press', 'https://www.youtube.com/watch?v=HXrLaqNIkTs'),
    ('plank', 'https://www.youtube.com/watch?v=L2jO3DvocWA'),
    ('pulley frente', 'https://www.youtube.com/shorts/VqDU1A5oVJo'),
    ('pulley frente pegada fechada', 'https://www.youtube.com/watch?v=U8Z9_Ny_uw0'),
    ('pull up', 'https://www.youtube.com/watch?v=aAggnpPyR6E'),
    ('strict pull up', 'https://www.youtube.com/watch?v=aAggnpPyR6E'),
    ('quadruped hover', 'https://www.youtube.com/watch?v=3oLrQzkPG00'),
    ('remada baixa', 'https://www.youtube.com/watch?v=f8AVh4VBbos'),
    ('remada curvada', 'https://www.youtube.com/shorts/e53vSzibkO0'),
    ('rosca direta', 'https://www.youtube.com/shorts/AEXkxZe7HBo'),
    ('rotação de tornozelos', 'https://www.youtube.com/watch?v=uGFIUlF88PA'),
    ('rotação de tronco', 'https://www.youtube.com/watch?v=Q1FKHldSEgQ'),
    ('rotação externa isométrica', 'https://www.youtube.com/shorts/Rybv5CCAHlk'),
    ('remada unilateral (serrote)', 'https://www.youtube.com/shorts/NBmXCNUYrAk'),
    ('stiff', 'https://www.youtube.com/shorts/eGIp1JqV_PM'),
    ('tabata core', 'https://www.youtube.com/watch?v=xdmvae0tKdI'),
    ('tríceps pulley', 'https://www.youtube.com/shorts/UdfF_LQ1iak'),
    ('walking lunge', 'https://www.youtube.com/watch?v=DlhojghkaQ0'),
    ('wall sit', 'https://www.youtube.com/watch?v=cWTZ8Am1Ee0'),
    ('ytwl', 'https://www.youtube.com/watch?v=Lk9ot_6zquk'),
    ('supine serratus punches', 'https://www.youtube.com/watch?v=r5byDDl3Ri8'),
    ('wood chops com elástico', 'https://www.youtube.com/watch?v=Yp2DmHk3KnY'),
    ('perdigueiro (bird-dog)', 'https://www.youtube.com/shorts/YO9bbyrgJkI'),
    ('side plank', 'https://www.youtube.com/shorts/BFOyHDlY2UE'),
    ('banded wood chops', 'https://www.youtube.com/shorts/64RP6a4zK7Q'),
    ('cardio leve', 'https://drive.google.com/file/d/1nsWhiyaEPMuauziOdkZhepHdan-_IeER/view?usp=drive_link'),
    ('world''s greatest stretch', 'https://www.youtube.com/shorts/7XheaZERvBQ'),
    ('globet squat', 'https://www.youtube.com/shorts/lRYBbchqxtI'),
    ('scapular pull-ups', 'https://www.youtube.com/shorts/9M8ylnbriB0'),
    ('strict press', 'https://www.youtube.com/watch?v=J9nSWwSXUbU'),
    ('strict pull-ups', 'https://www.youtube.com/watch?v=HRV5YKKaeVw'),
    ('supino', 'https://www.youtube.com/shorts/UHa9U-O09_U'),
    ('for time 21-15-9', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('mobilidade de punho e front rack', 'https://www.youtube.com/watch?v=zhWIHLhPV-U'),
    ('goblet squat', 'https://www.youtube.com/shorts/YHEh8i6R5DE'),
    ('metcon - for time 21-15-9', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=sharing'),
    ('clean pulls', 'https://www.youtube.com/watch?v=RnbJcrtOaB0'),
    ('lpo - clean & jerk complex', 'https://www.youtube.com/shorts/J2YH8S6-Pss'),
    ('emom', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=sharing'),
    ('abdução de quadril com miniband', 'https://www.youtube.com/shorts/_mUl4gNZkjI'),
    ('glute bridge', 'https://www.youtube.com/shorts/ktSiNvWzYWY'),
    ('progressção de carga no deadlift', 'https://www.youtube.com/watch?v=l6gDwf3xC6s'),
    ('rosca martelo', 'https://www.youtube.com/shorts/GilFwBs_kOs'),
    ('ativação', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('metcon', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('pigeon pose', 'https://www.youtube.com/watch?v=wePPX_zzYKY'),
    ('couch stretch', 'https://www.youtube.com/watch?v=ZAt7KE4AUNo'),
    ('dead bug (pressão)', 'https://www.youtube.com/watch?v=CVftVCJwLoo'),
    ('y-t-w (chão)', 'https://www.youtube.com/watch?v=v6p7aiVuPy4'),
    ('push-ups com déficit', 'https://www.youtube.com/watch?v=4kqlnmUL8kE'),
    ('pogo jumps', 'https://www.youtube.com/watch?v=j0nl5dWuqN4'),
    ('penguin taps', 'https://www.youtube.com/watch?v=H-m3t33fM_I'),
    ('skill - double unders', 'https://www.youtube.com/watch?v=q3ObwHuj9CE'),
    ('glute bridge unilateral', 'https://www.youtube.com/watch?v=Zb3ILLdI6fk'),
    ('aquecimento back squat', 'https://www.youtube.com/watch?v=YqUT087hHf8'),
    ('mobilidade ativa', 'https://www.youtube.com/watch?v=o4d5nx1FA0k'),
    ('aquecimento ombro', 'https://www.youtube.com/shorts/IlqmuM9FPUU'),
    ('ginástica', 'https://www.youtube.com/watch?v=xX9Hzi7Onnw'),
    ('aquecimento clean', 'https://www.youtube.com/watch?v=-hutN9oo-bU'),
    ('lpo - clean & jerk', 'https://www.youtube.com/watch?v=nJEMcnFKWQ8'),
    ('aquecimento deadlift', 'https://www.youtube.com/watch?v=Qpr5i4DTpk0'),
    ('alongamento flexores', 'https://www.youtube.com/shorts/Mh1FgwOVQB4'),
    ('aquecimento corrida', 'https://www.youtube.com/watch?v=3WUtJxLv-wI'),
    ('corrida de rua', 'https://www.youtube.com/watch?v=wRkeBVMQSgg'),
    ('wod - leg burner', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('wod - shoulder safe', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('wod - anaerobic power', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('wod - the heavy one', 'https://drive.google.com/file/d/11NdN0lzg1UEAmwS6eDT7MyGBT2fMLtkc/view?usp=drive_link'),
    ('caminhada recuperação', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link'),
    ('descanso total', 'https://drive.google.com/file/d/10gHzz-rLM1esjYYUYhYk_mxaI7SzfXVd/view?usp=drive_link')
ON CONFLICT (name) DO UPDATE SET link = EXCLUDED.link;
