-- ============================================================
-- Populate missing session_types in the icons table
-- so that sessions generated by the AI Coach don't violate
-- the FK constraint sessions.session_type → icons.session_type
--
-- Strategy: insert all known AI-generated session types using
-- the crossfit icon as a safe default. Already-existing rows
-- are skipped via ON CONFLICT DO NOTHING.
-- ============================================================

-- The img path mirrors the existing crossfit icon as a safe default.
-- You can update the img path later per type via the Supabase dashboard.
INSERT INTO public.icons (session_type, img)
VALUES
  -- Already exist but listed for safety (ON CONFLICT DO NOTHING)
  ('Calistenia',            'assets/sessions_icons/calistenia_session_icon.png'),
  ('Core',                  'assets/sessions_icons/core_session_icon.png'),
  ('Crossfit',              'assets/sessions_icons/crossfit_session_icon.png'),
  ('LPO',                   'assets/sessions_icons/lpo_session_icon.png'),
  ('Mobilidade',            'assets/sessions_icons/mobility_session_icon.png'),
  ('Recuperação Ativa',     'assets/sessions_icons/recovery_session_icon.png'),
  ('Relax',                 'assets/sessions_icons/relax_session_icon.png'),
  ('Run',                   'assets/sessions_icons/run_session_icon.png'),
  ('Strengh',               'assets/sessions_icons/strengh_session_icon.png'),
  ('Swimming',              'assets/sessions_icons/swimming_session_icon.png'),

  -- AI-generated types that currently BREAK the FK (using crossfit icon as default)
  ('Acessório',             'assets/sessions_icons/crossfit_session_icon.png'),
  ('Acessórios-Blindagem',  'assets/sessions_icons/crossfit_session_icon.png'),
  ('Cardio',                'assets/sessions_icons/run_session_icon.png'),
  ('Cardio-Mobilidade',     'assets/sessions_icons/mobility_session_icon.png'),
  ('Core Strength',         'assets/sessions_icons/core_session_icon.png'),
  ('Core-Prep',             'assets/sessions_icons/core_session_icon.png'),
  ('Descanso',              'assets/sessions_icons/relax_session_icon.png'),
  ('EMOM',                  'assets/sessions_icons/crossfit_session_icon.png'),
  ('Endurance',             'assets/sessions_icons/run_session_icon.png'),
  ('FBB',                   'assets/sessions_icons/crossfit_session_icon.png'),
  ('Força-Heavy',           'assets/sessions_icons/strengh_session_icon.png'),
  ('Força-Metcon',          'assets/sessions_icons/crossfit_session_icon.png'),
  ('Força-Skill',           'assets/sessions_icons/crossfit_session_icon.png'),
  ('Full Body Pump',        'assets/sessions_icons/crossfit_session_icon.png'),
  ('Full Session',          'assets/sessions_icons/crossfit_session_icon.png'),
  ('Ginástica-Metcon',      'assets/sessions_icons/calistenia_session_icon.png'),
  ('Hipertrofia',           'assets/sessions_icons/strengh_session_icon.png'),
  ('Hipertrofia-Blindagem', 'assets/sessions_icons/strengh_session_icon.png'),
  ('LPO-Força-Metcon',      'assets/sessions_icons/lpo_session_icon.png'),
  ('LPO-Metcon',            'assets/sessions_icons/lpo_session_icon.png'),
  ('LPO-Potência',          'assets/sessions_icons/lpo_session_icon.png'),
  ('Metcon',                'assets/sessions_icons/crossfit_session_icon.png'),
  ('Mobilidade-Flow',       'assets/sessions_icons/mobility_session_icon.png'),
  ('Mobilidade-Cardio',     'assets/sessions_icons/mobility_session_icon.png'),
  ('Mobilidade-Core',       'assets/sessions_icons/mobility_session_icon.png'),
  ('Mobilidade-Inferiores', 'assets/sessions_icons/mobility_session_icon.png'),
  ('Mobilidade-Prep',       'assets/sessions_icons/mobility_session_icon.png'),
  ('Multi',                 'assets/sessions_icons/crossfit_session_icon.png'),
  ('Musculação',            'assets/sessions_icons/strengh_session_icon.png'),
  ('Musculação-Cardio',     'assets/sessions_icons/crossfit_session_icon.png'),
  ('Musculação-Funcional',  'assets/sessions_icons/crossfit_session_icon.png'),
  ('Musculação-Força',      'assets/sessions_icons/strengh_session_icon.png'),
  ('Natação',               'assets/sessions_icons/swimming_session_icon.png'),
  ('Prehab',                'assets/sessions_icons/recovery_session_icon.png'),
  ('Prehab-Força',          'assets/sessions_icons/recovery_session_icon.png'),
  ('Prehab-Mobilidade',     'assets/sessions_icons/recovery_session_icon.png'),
  ('Reintrodução-FBB',      'assets/sessions_icons/crossfit_session_icon.png'),
  ('Skill',                 'assets/sessions_icons/calistenia_session_icon.png'),
  ('Skill-Metcon',          'assets/sessions_icons/crossfit_session_icon.png')
ON CONFLICT (session_type) DO NOTHING;
